name: Build images / docs
on: [push]

# Cancel if a newer run is started
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  rich_codex:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Install requirements for docs
        run: pip install cowsay lolcat mkdocs-material pillow cairosvg

      - name: Generate terminal images with rich-codex
        uses: ./ # Would normally be ewels/rich-codex@v1
        with:
          commit_changes: "true"
          clean_img_paths: docs/img/*.svg

      - name: Build and deploy docs
        run: mkdocs gh-deploy --force
